### PR TITLE
fix: type for support Express4 router and so on

### LINKED ISSUE #20: needs IRouter?
I tried to use expressListRoutes within my node.js/typescript app.
```
import expressListRoutes from 'express-list-routes';

const routes = express.Router();
...
console.log('::: Available routes are:');
expressListRoutes(routes);

```
which gave: 
```
src/routes/index.ts:15:19 - error TS2345: Argument of type 'Router' is not assignable to parameter of type 'ExpressApp'.
  Property '_router' is missing in type 'IRouter' but required in type 'ExpressApp'.
```

any information or hint, where I might be using it wrongly?

### PR DESCRIPTION
**Pull request by yutak23**
This ought to fix https://github.com/labithiotis/express-list-routes/issues/20.

Type definitions have been modified to accommodate all Express 3, 4, and 5.

Also, router is now supported.

### CODE REVIEW

File: index.d.ts [hunk 1]
```diff
@@ -2,27 +2,39 @@ interface Options {
...
+  // Express 5
+  router?: {
+    stack: Layer[];
   };
 }
 
 declare function expressListRoutes(app: ExpressApp, options?: Options): Array<{ method: string; path: string }>;
 
-export { expressListRoutes as default };
+export = expressListRoutes;
```
Comment (yutak23) [inline index.d.ts:40]: ESM seems incompatible in CommonJS PJs with default export (see https://github.com/microsoft/TypeScript/issues/52086).

Therefore, the existing type definition will result in the following error.

```
This expression is not callable.
  Type 'typeof import("/home/study/workspace/ts-node-oidc/node_modules/express-list-routes/index")' has no call signatures.
```

By setting `export =`, both CommonJS and ES Module can be supported.

File: index.d.ts [hunk 2]
```diff
@@ -2,27 +2,30 @@ interface Options {
...
+  // Express 4, 5 Router
+  stack?: Layer[];
+  // Express 5
+  router?: { stack: Layer[] } | string;
 }
 
 declare function expressListRoutes(app: ExpressApp, options?: Options): Array<{ method: string; path: string }>;
 
-export { expressListRoutes as default };
+export = expressListRoutes;
```
Comment (yutak23) [inline index.d.ts:31]: ESM seems incompatible in CommonJS PJs with default export (see https://github.com/microsoft/TypeScript/issues/52086).

Therefore, the existing type definition will result in the following error.

```
This expression is not callable.
  Type 'typeof import("/home/study/workspace/ts-node-oidc/node_modules/express-list-routes/index")' has no call signatures.
```

By setting `export =`, both CommonJS and ES Module can be supported.

**Comment by yutak23** [comment]
@labithiotis 

I would appreciate it if you could review and respond to the content of the PR.

File: index.d.ts [hunk 3]
```diff
@@ -2,27 +2,30 @@ interface Options {
   spacer?: number;
   prefix?: string;
   logger?: (method: string, space: string, path: string) => void;
+  color?: boolean;
 }
 
 interface Route {
-  method?: string;
+  method?: string | object;
```
Comment (labithiotis) [inline index.d.ts:9]: @yutak23 Do we know the shape of the object for the method so we can tighten it up more? 

Looking at @types/express it just defines it as any :( 

Happy to leave as object but wanted to ask the question.

**Review by labithiotis — APPROVED** [review]
@yutak23 Thank you so much for submitting this PR. Sorry for missing the PR/Issue - seems my GH notifications are still not working correctly for this repo :(

File: index.d.ts (hunk 3 above)
Comment (yutak23) [reply index.d.ts:9]: @labithiotis 

> Do we know the shape of the object for the method so we can tighten it up more?

Yes, I think it is possible.
However, I think it would take a lot of effort to define it in interface or type, and to define the type for each version of Express.

Therefore, I adopted `object` this time as a compromise (because `any` would allow impossible things such as `number` and `boolean`).
